name: ☝️ Notify new release ready to deploy

on:
  release:
    types: [published]

jobs:
  send-notification:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.RELEASE_NOTIFICATION__SLACK_WEBHOOK_URL }}
        with:
          payload: |
            {
              "n8n_version": "value"
            }
